POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RhYWphcHJvIiwiaWQiOiI2MGMyNWQyOTkzMWQ3M2YxMThmZmFhM2EiLCJpYXQiOjE2MjMzNTI0NTd9.BKR2ObItRk9av3mm8urjyAEFrDN2n7hJhQHwJSSr9bU


{
  "title": "tokenitesti22",
  "author": "tokenMan",
  "url": "www.tokenitoen.fi",
  "likes": 23423423,
  "userId": "60c25d29931d73f118ffaa3a"
}